### ISSUE TITLE
Passing multiple index corrections to straxen

### ISSUE THREAD

**Issue by LuisSanchez25** [XENONnT/xedocs#1]
* xedocs version: 0.1.25
* Python version: 3.8.13
* Operating System: Ubuntu 

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Use correction with partition indices in xedocs to reprocess data.
I was able to use the URLConfig to give straxen the desired data, straxen recognized the data-type as a list. When I tried to reprocess the corrected areas with the partitions I ran into an error and was unable to reprocess the data.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

`import straxen
import strax
import xedocs
import rframe'

`class AvgSEGain(xd.schemas.base_corrections.TimeSampledCorrection):
    #from typing import Literal
    
    _ALIAS = "avg_se_gain"
    #PARTITION = Literal["all_tpc", "ab", "cd"]
    partition: xd.schemas.constants.PARTITION = rframe.Index(default='all_tpc')
    value: float

st_xd = straxen.contexts.xenonnt_online()
st = straxen.contexts.xenonnt_online()

st_xd.set_config({"avg_se_gain":"xedocs://"
                  "avg_se_gain"
                  "?version=v!&run_id=047122&partition=['ab','cd']&attr=value"})

run_id2 = '047122'

zz = st_xd.get_single_plugin(run_id2, 'corrected_areas')
zz.avg_se_gain`

Result : 
[29.79008228892991, 31.714796399916082]

`kr_ei_xd = st_xd.get_array(run_id2, 'event_info')`

Crash Traceback:
Exception in thread build:corrected_areas:
Traceback (most recent call last):
  File "/opt/conda/envs/strax/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    Target Mailbox (event_info) killed, exception <class 'strax.mailbox.MailboxKilled'>, message (<class 'ValueError'>, ValueError('operands could not be broadcast together with shapes (78334,) (2,) '), <traceback object at 0x7f9a9ef3ec40>)
self.run()
  File "/opt/conda/envs/strax/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/strax/mailbox.py", line 294, in _send_from
Exception in thread load:event_basics    self.kill_from_exception(e)
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/strax/mailbox.py", line 213, in kill_from_exception
    raise e
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/strax/mailbox.py", line 281, in _send_from
    x = next(iterable)
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/strax/plugins/plugin.py", line 499, in iter
    yield self.do_compute(chunk_i=chunk_i, **inputs_merged):
Traceback (most recent call last):
  File "/opt/conda/envs/strax/lib/python3.8/threading.py", line 932, in _bootstrap_inner

    self.run()
  File "/opt/conda/envs/strax/lib/python3.8/threading.py", line 870, in run
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/strax/plugins/plugin.py", line 607, in do_compute
    self._target(*self._args, **self._kwargs)
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/strax/mailbox.py", line 297, in _send_from
        self.close()
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/strax/mailbox.py", line 361, in close
result = self.compute(**kwargs)
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/straxen/plugins/event_processing.py", line 835, in compute
    self.send(StopIteration)
  File "/home/luissanchez25/.local/lib/python3.8/site-packages/strax/mailbox.py", line 313, in send
        cs2_top_wo_elifecorr = cs2_top_xycorr[partition_mask] / seg_ee_corr
ValueError: operands could not be broadcast together with shapes (78334,) (2,) 
raise MailboxKilled(self.killed_because)
strax.mailbox.MailboxKilled: (<class 'ValueError'>, ValueError('operands could not be broadcast together with shapes (78334,) (2,) '), <traceback object at 0x7f9a9ef3ec40>)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [15], in <cell line: 1>()
----> 1 kr_ei_xd = st_xd.get_array(run_id2, 'event_info')
      2 kr_ei = st.get_array(run_id2, 'event_info')

File ~/.local/lib/python3.8/site-packages/strax/context.py:1440, in Context.get_array(self, run_id, targets, save, max_workers, **kwargs)
   1433 else:
   1434     source = self.get_iter(
   1435         run_ids[0],
   1436         targets,
   1437         save=save,
   1438         max_workers=max_workers,
   1439         **kwargs)
-> 1440     results = [x.data for x in source]
   1442 results = np.concatenate(results)
   1443 return results

File ~/.local/lib/python3.8/site-packages/strax/context.py:1440, in <listcomp>(.0)
   1433 else:
   1434     source = self.get_iter(
   1435         run_ids[0],
   1436         targets,
   1437         save=save,
   1438         max_workers=max_workers,
   1439         **kwargs)
-> 1440     results = [x.data for x in source]
   1442 results = np.concatenate(results)
   1443 return results

File ~/.local/lib/python3.8/site-packages/strax/context.py:1321, in Context.get_iter(self, run_id, targets, save, max_workers, time_range, seconds_range, time_within, time_selection, selection_str, keep_columns, drop_columns, allow_multiple, progress_bar, _chunk_number, **kwargs)
   1316     generator.throw(OutsideException(
   1317         "Terminating due to an exception originating from outside "
   1318         "strax's get_iter (which we cannot retrieve)."))
   1320 except Exception as e:
-> 1321     generator.throw(e)
   1322     raise ValueError(f'Failed to process chunk {n_chunks}!')
   1324 if not seen_a_chunk:

File ~/.local/lib/python3.8/site-packages/strax/context.py:1293, in Context.get_iter(self, run_id, targets, save, max_workers, time_range, seconds_range, time_within, time_selection, selection_str, keep_columns, drop_columns, allow_multiple, progress_bar, _chunk_number, **kwargs)
   1291 pbar.last_print_t = time.time()
   1292 pbar.mbs = []
-> 1293 for n_chunks, result in enumerate(strax.continuity_check(generator), 1):
   1294     seen_a_chunk = True
   1295     if not isinstance(result, strax.Chunk):

File ~/.local/lib/python3.8/site-packages/strax/chunk.py:303, in continuity_check(chunk_iter)
    300 last_runid = None
    302 last_subrun = {'run_id': None}
--> 303 for chunk in chunk_iter:
    304     if chunk.run_id != last_runid:
    305         last_end = None

File ~/.local/lib/python3.8/site-packages/strax/processor.py:302, in ThreadedMailboxProcessor.iter(self)
    296 if exc is not None:
    297     # Reraise exception. This is outside the except block
    298     # to avoid the 'during handling of this exception, another
    299     # exception occurred' stuff from confusing the traceback
    300     # which is printed for the user
    301     self.log.debug("Reraising exception")
--> 302     raise exc.with_traceback(traceback)
    304 # Check the savers for any exception that occurred during saving
    305 # These are thrown back to the mailbox, but if that has already closed
    306 # it doesn't trigger a crash...
    307 # TODO: add savers inlined by parallelsourceplugin
    308 # TODO: need to look at plugins too if we ever implement true
    309 # multi-target mode
    310 for k, saver_list in self.components.savers.items():

File ~/.local/lib/python3.8/site-packages/strax/mailbox.py:281, in Mailbox._send_from(self, iterable)
    276                 raise MailboxReadTimeout(
    277                     f"{self} could not progress beyond {i}, "
    278                     f"no driving subscriber requested it.")
    280 try:
--> 281     x = next(iterable)
    282 except StopIteration:
    283     # No need to send this yet, close will do that
    284     break

File ~/.local/lib/python3.8/site-packages/strax/plugins/plugin.py:499, in Plugin.iter(self, iters, executor)
    497             yield new_future
    498         else:
--> 499             yield self.do_compute(chunk_i=chunk_i, **inputs_merged)
    501 except IterDone:
    502     # Check all sources are exhausted.
    503     # This is more than a check though -- it ensure the content of
    504     # all sources are requested all the way (including the final
    505     # Stopiteration), as required by lazy-mode processing requires
    506     for d in iters.keys():

File ~/.local/lib/python3.8/site-packages/strax/plugins/plugin.py:607, in Plugin.do_compute(self, chunk_i, **kwargs)
    605     kwargs['start'] = start
    606     kwargs['end'] = end
--> 607 result = self.compute(**kwargs)
    609 return self._fix_output(result, start, end)

File ~/.local/lib/python3.8/site-packages/straxen/plugins/event_processing.py:835, in CorrectedAreas.compute(self, events)
    832 seg_ee_corr = seg[partition]/avg_seg[partition]*ee[partition]
    834 # note that these are already masked!
--> 835 cs2_top_wo_elifecorr = cs2_top_xycorr[partition_mask] / seg_ee_corr
    836 cs2_bottom_wo_elifecorr = cs2_bottom_xycorr[partition_mask] / seg_ee_corr
    838 result[f"{peak_type}cs2_wo_elifecorr"][partition_mask] = cs2_top_wo_elifecorr + cs2_bottom_wo_elifecorr

ValueError: operands could not be broadcast together with shapes (78334,) (2,) 

 
```

**Comment by jmosbacher** [comment]
I would recommend adding a small protocol that takes a list of documents as its argument + a keyword argument for the key and one for the value and have it return a dictionary where the keys and values are the attributes from the document.
something like:

```python
@URLConfig.register('docs-to-dict')
def docs_to_dict(docs: list, key_attr=None, value_attr='value'):
    if not isinstance(docs, list):
        raise TypeError(f'The docs-to-dict protocol expects a list of documents but received {type(docs)} instead.')
    result = {}
    for i, doc in enumerate(docs):
        key = i if key_attr is None else getattr(doc, key_attr)
        result[key] = getattr(doc, value_attr)
    return result
```

For the example given here the URL would then be:

```python
st_xd.set_config({"avg_se_gain":"docs-to-dict://xedocs://"
                  "avg_se_gain"
                  "?version=v!&run_id=047122&partition=['ab','cd']&key_attr=partition&value_attr=value"})
```
